name: Generate ascii workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout-repo
              uses: actions/checkout@v6           

            - name: Read and List file
              run: ls -ltra
            - name: Executing Shell Script
              run: ./ascii-script.sh
                   

